# cfar
GUARD_CELLS: 30
BG_CELLS: 30
ALPHA: 1.8

# image pyramid
ratio: 0.7071
layers: 2

# path
OUTPUT_IMG_DIR: 'test1_out'
root: 'test1'

# configs
saveResult: True     # save to file
cropEdge: True       # reset edge pixs to zero, something looks like 'reversed padding'
threading: 10
useGPU: True
measureCommand: True # show running time