# cfar
GUARD_CELLS: 15
BG_CELLS: 15
ALPHA: 2

# image pyramid
ratio: 0.7071
layers: 4

# path
OUTPUT_IMG_DIR: 'test_out'
root: 'test'

# configs
saveResult: False     # save to file
cropEdge: True       # reset edge pixs to zero, something looks like 'reversed padding'
threading: 10
useGPU: True
measureCommand: True # show running time